### ISSUE TITLE
Build instructions for windows

### ISSUE THREAD

**Issue by MrAngry777** [hjweide/a-star#3]
Would be possible to provide a make file for windows in CMAKE? Or to provide instructions on how to make a build?

**Comment by hjweide** [comment]
@MrAngry777 There is already a makefile included in the repository, so there's no need to use cmake (even on Windows).  The build instructions are [here](https://github.com/hjweide/a-star#usage).  You can either just run ```make``` in the directory where you cloned the repository to use the provided makefile, or you can compile it directly with the following command from the terminal or your preferred IDE:

`g++ astar.cpp -O3 -Wall -shared -fpic -o astar.so`

I hope that helps.

**Comment by hjweide** [comment]
Closing.  Please let me know if you're still stuck.
