### ISSUE TITLE
How do I make Makefile in win64

### ISSUE THREAD

**Issue by AlexeyVolosnikov** [hjweide/a-star#4]
When I type in cmd
`make Makefile`
it returns
`make: Nothing to be done for 'Makefile'`. How to use makefile for creating .so object ?

What should I do for creating .so file, could you help?

**Comment by hjweide** [comment]
Were you able to get it working?  If I have some time in the near future I want to make this pip-installable, which should hopefully simplify the process.

**Comment by AlexeyVolosnikov** [comment]
@hjweide I should have typed only `make`, not `make Makefile`. It worked fine, but it is not working on win64, only on linux. 
Could I know are you going to make it working on win64? It is the only working algorithm that I found over the internet that could be run on python and have such a speed

**Comment by hjweide** [comment]
If I have time I want to see if I can get it working on Windows, but I don't have a Windows machine to test on so it might take me a while.  Let me see what I can do.  If you know how to do this and want to submit a PR you're also free to do so.

I'm curious about this speed comparison.  Did you benchmark if against other implementations?  I haven't done this myself but would be interested in the resuts.

**Comment by AlexeyVolosnikov** [comment]
I didn't compare actual results in seconds, but almost all algorithms (Python) are showing graphical representation of algorithm so it has much less speed without any speed detection. For the other algorithms (that are written in Python and calculate without graphical repr.) it usually takes several seconds comparing to your program (0.4s) .

I don't know about other algorithms that are written in C++ because I need to use it from python and other authors don't provide such an option (and I didn't tried to make my own). Now I don't know how to make it run on windows, so I just will continue working on linux :)

If I will use pathfinding algorithms in c++ I will let you know about your prog. run results in sec comparing to other algorithms

**Comment by hjweide** [comment]
You won't be able to run it on Windows with the current code.  If I can find some time this weekend I'll try to get it working on Windows.
